learning_templates/basic_app/urls.py
from django.urls import path
from . import views

app_name= 'basic_app'

urlpatterns = [
    #path('',views.index,name='index'),
    path('other/',views.other,name='other'),
    path('relative/',views.relative,name='relative'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    index_dict = {
        'index':'Inserted in Index Page by Django'
    }
    return render(request,'basic_app/index.html',context=index_dict)

def other(request):
    other_dict = {
        'other':'Inserted in Other page by Django'
    }
    return render(request,'basic_app/other.html',context=other_dict)

def relative(request):
    relative_dict = {
        'relative':'Inserted in Relative page by Django'
    }
    return render(request,'basic_app/relative.html',context=relative_dict)

learning_templates/basic_app/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>Relative Page</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'index' %}">Index</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'basic_app:relative' %}">Relative<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'basic_app:other' %}">Other</a>
            </li>
          </ul>
        </div>
      </nav>
      {% block body_block %}
      {% endblock%}
</body>
</html>

learning_templates/basic_app/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
{% block body_block %}
<p align="center">Index Page</p>
<div align="center">
    {{index|upper}}
</div>
{% endblock %}

learning_templates/basic_app/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
{% block body_block %}
<p align="center">Other page</p>
<div align="center">
    {{other|lower}}
</div>
{% endblock %}

learning_templates/basic_app/templates/basic_app/relative.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
{% block body_block %}
{% load filters %}
<p align="center">Relative Page</p>
<div align="center">
    {{relative|func:" hello"}}
</div>
{% endblock %}