learning_user/basic_app/urls.py
from django.urls import path
from . import views 

app_name='basic_app'

urlpatterns = [
    path('registration/',views.registration,name='registration'),
    path('user_login/',views.user_login,name='user_login'),
]

learning_user/learning_user/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('special/',views.special,name='special'),
    path('logout/',views.user_logout,name='logout'),
    path('basic_app/',include('basic_app.urls')),
]

learning_user/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio = models.URLField(blank=True)
    picture = models.ImageField(upload_to='basic_app/profile_pics',blank = True)

    def __str__(self):
        return self.user.username

learning_user/basic_app/forms.py
from django import forms
from basic_app.models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio','picture')

learning_user/basic_app/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo
from basic_app.forms import UserForm,UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout

# Create your views here.

def index(request):
    return render(request,'basic_app/index.html')

@login_required
def special(request):
    return HttpResponse("Hey! you are logged in!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def registration(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            
            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'basic_app/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user :
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not active')
        else :
            print('Invalid User')
            return HttpResponse('Invalid User')
    else :
        return render(request,'basic_app/login.html', {})

learning_user/basic_app/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>My Web Page</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'admin:index' %}">Admin</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index' %}">Index<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'basic_app:registration' %}">Registration</a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'basic_app:user_login' %}">Log In</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>
      {% block body_block %}
      {% endblock%}
</body>
</html>

learning_user/basic_app/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
<div class="container">
    <div class="jumbotron">
        <h2>Welcome!</h2>
        <h4>Index Page</h4>
    </div>
</div>
{% endblock %}

learning_user/basic_app/templates/basic_app/login.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
<div class='container'>
    <div class='jumbotron'>
        <h2>Login !</h2>
        <form method="post" action="{% url 'basic_app:user_login' %}" >
            {% csrf_token %}
            <label for="username">UserName:</label>
            <input type="text" name="username" placeholder="Enter UserName:">
            <label for="password">password:</label>
            <input type="password" name="password" >
            <input type="submit"  value="Log In">
        </form>
    </div>
</div>
{% endblock %}

learning_user/basic_app/templates/basic_app/registration.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
<div class="container">
    <div class="jumbotron">
        {% if registered %}
            <h2>Thank You !</h2>
        {% else %}
            <h2>Register here</h2>
            <h2>Fill the form below</h2>
            <form enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" name="" value="register">
            </form>
        {% endif %}
    </div>
    
</div>
{% endblock %}